### ISSUE TITLE
*Bug Fix - Diversos erros em Payment.php

### ISSUE THREAD

**Issue by Fertusco** [lucassdoliveira/cielo3.0#20]
Prezado Lucas, boa tarde.

Corrigimos todos os erros do módulo e validamos junto ao SandBox da Cielo via PostMan.

Listarei alguns deles:

### Campo QuotePaymentId na tabela sales_flat_order_payment### 

No arquivo payment.php, na funcão de autorização da transação, o módulo salva o token no campo QuotePaymentId da tabela sales_flat_order_payment no BD, porém esta tabela é para tipo inteiros e o token é uma string. Desta forma o módulo não consegue consultar as transações nem capturar o pedido junto a Cielo. (linha 402)

### Mage::dispatchEvent em diversas partes do código ### 

O módulo está usando Mage::dispatchEvent com o comentário de logar as variáveis, porém está sendo gerado um evento que não está sendo escutado por nenhum observer. O ideal seria trocar por Mage::log.

### Captura ### 

Para que as transações sejam capturadas, o módulo tem que fazer o storage do token correto recebido na autorização. Porém mesmo retornando código 6 (transação capturada com sucesso), o código para na exceção da linha 472 em decorrência do if da linha 463. Basta alterar "!==" para "!=".

### Linha 469

 `'message' => (string) $retorno->ReturnMessage() `

Este método é inválido, e deve ser alterado para:

`'message' => (string) $retorno->getReturnMessage(),`

### setAdditionalInformation

Após a captura da transação, não está sendo gravado o código na coluna AdditionalInformation no bd, desta forma, não aparece o pedido como capturado nas informações do backend, mesmo após a captura. É necessário adicionar a seguinte linha à função:

`$payment->setAdditionalInformation('captura_codigo', (string) $retorno->getReturnCode());`

Ainda tem alguns erros que eu não listei na parte de cancelamento.

Já fiz um fork do projeto e criei uma branch com todas as alterações para que o módulo funcione sem erros, se achar necessário, me avise e submeto um pull request.

Abraços.

**Comment by lucassdoliveira** [comment]
Olá Fertusco, agradeço sua contribuição para esse módulo. Isso fortalece a cada dia mais nossa comunidade.

Poderia submeter as modificações ? qualquer dúvida pode entrar em contato pelo e-mail atendimento@nitroecom.com.br

**Comment by Fertusco** [comment]
Claro @lucassdoliveira 

Esta semana foi bem corrida, mas no final de semana vou subir todas as alterações no módulo. Tem alguns outros pontos, mas aí vamos falando ao longo do tempo. Assim que submeter o PR, aviso você!

Vou deixar este issue marcado como fechado.
